version: '3'

services:
  server:
    build: ./server
    expose:
      - "3000"
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
    command: npm start
  client:
    build: ./client
    environment:
      - REACT_APP_PORT:${REACT_APP_PORT}
    expose: 
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    links:
      - server
    command: npm run start


